// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAuYqrJ_vmNFuy9Wc5WXNMKOxQ5pJnaSTg',
//     appId: '1:726797624977:web:874c978302e9b922ca8130',
//     messagingSenderId: '726797624977',
//     projectId: 'unilever-activo',
//     authDomain: 'unilever-activo.firebaseapp.com',
//     storageBucket: 'unilever-activo.appspot.com',
//     measurementId: 'G-5THLH5386Q',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyA8RdnYxv38DTQGawruuBKogSRSzq4cY40',
//     appId: '1:726797624977:android:3404a57a42de3838ca8130',
//     messagingSenderId: '726797624977',
//     projectId: 'unilever-activo',
//     storageBucket: 'unilever-activo.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBFp4RB3dNEmVnXSQe42mzYDTmieBmq-R4',
//     appId: '1:726797624977:ios:ec3b6fe0b27eec3aca8130',
//     messagingSenderId: '726797624977',
//     projectId: 'unilever-activo',
//     storageBucket: 'unilever-activo.appspot.com',
//     iosBundleId: 'com.unilever.unileverActivo',
//   );
// }
